#-------------------------------
# General Site Settings

title: opensensorsdata
name: opensensorsdata srl
description: shape data to shape society
email: contact@opensensorsdata.it
author: opensensorsdata srl
url: www.opensensorsdata.it
baseurl: /
avatar: "/assets/img/sfondo/kndnsk_facebook.png"

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: <i class="fa fa-github fa-lg"></i>, url: 'https://github.com/opensensorsdata'}
- {name: <i class="fa fa-twitter fa-lg"></i>, url: 'http://twitter.com/osd_it'}
- {name: <i class="fa fa-medium fa-lg"></i>, url: 'https://medium.com/opensensorsdata-review'}
- {name: <i class="fa fa-hand-spock-o fa-lg"></i>, url: '#manifesto'}
- {name: <i class="fa fa-shopping-basket fa-lg"></i>, url: '#work'}
- {name: <i class="fa fa-envelope-o fa-lg"></i>, url: '#contact'}
- {name: <i class="fa fa-archive fa-lg"></i>, url: 'http://doc.opensensorsdata.it'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: '// shape data to shape society // We provide methods to model and shape the strategic value of information. We are an internet company committed to open access to data. Our goal is to empower people to shape society and busineness by shaping data, brick after brick'
  rel-author: 'http://doc.opensensorsdata.it/pages/about/'
  rel-publisher: 'https://medium.com/opensensorsdata-review'
  images: 'assets/img/sfondo'
  fb_appid: 306483466188566
  fb_admins: https://www.facebook.com/luca.corsato



#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: UA-62992830-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

intro: >
  In the digital era information is power. We provide methods to model and shape the strategic value of information. We are an internet company committed to open access to data. Our goal is to empower people to shape society and busineness by shaping data, brick after brick'

#activity:
#- {title: 'access to data',
#  image: 'Lego_Brick.svg',
#  content: 'access to public data, both physical and digital,  through our opendatabank or store your private datastreams in one of our safe-deposit box'}
#- {title: 'build data into bricks',
#  image: 'Lego_dimensions.svg',
#  content: 'combine, compare and shape datastreams into meaningful charts'}
#- {title: 'share and reuse your bricks',
#  image: 'HSLego.svg',
#  content: 'publish your bricks and share with your community or use our private workspaces with your collaborators'}

activity:
- {title: 'design of data reuse',
  image: 'Lego_Brick.svg',
  content: '<a href="http://opensensorsdata.it">osd</a> is a company that design strategies and run projects of data reuse, making openness a core and sustainable element of business models. We trust in <a href="http://opendatahandbook.org/guide/en/what-is-open-data/">Open Data</a> and <a href="https://en.wikipedia.org/wiki/Open_business">Open Business</a>'}
- {title: 'market opportunities for data sharing',
  image: 'Lego_dimensions.svg',
  content: 'We provide consultancy to agencies, firms and charities. We focus on these market opportunities for data sharing and reuse that involve collaborative innovative programs and researches.'}
- {title: 'new way to make business',
  image: 'HSLego.svg',
  content: 'We arrange workshop and training to help third parties pipe their data and get the most out of their expertise. We help our customer to discover a whole new way to make business into an open networked market where they can systematically capture the value of their data.'}

#-------------------------------
# Manifesto Section

manifesto:
- {id: '1', intro: 'Internet is an agreement on how different networks can work together. We hold the internet in common, it doesn’t belong to anyone in particular.', total: 'For those who agree, Internet is a public good –everyone can use it and improve it– but the key value of the net is not built-in in its architecture. Internet is not optimised for specific purposes; in itself, internet is stupid –does nothing more than moving bits. It has no center, its key value is at its ends. Counting on the internet, everyone at each edge can offer services built on top of it. Counting on the agreement upon which the Internet is based, everyone at each edge can share data. The Internet enable a free market of innovation, where people with business ideas are not just free to engage with a marketplace, they create a marketplace throught conversations and connections. Edges are not points at which the internet ends, but where its value begin to be exploited. We are among those edges. We are an Internet company. That’s our posit.'}
- {id: '2', intro: 'Internet Companies are defined by what they own and see their markets as a target. We don’t.', total: ' We believe this is a fundamental misunderstanding of internet enabled innovation which is, at first, business and social innovation. We don’t target our market, we discuss with it: values, practices and a genuine points of view. There are no barbed wire fences between us and our customers; and will never be. If companies stop where community begins, then there is no market to innovate but just profit to make. Building fences might foster your business, for a while. But innovation is not about drawing “the Big Money” from the “Cash Cows”. It’s about making “the Big Money” a networked output, growing values between the edges of the net by opening up information. The innovation we hunt for is a collective pursuing of opportunities by informed citizens, customers and business people, as we are. It’s a long run. That’s what radical changes require.'}  
- {id: '3', intro: 'This is our commitment: to build an open economy in a networked market, where business concerns do not diverge from human concerns.', total: ' This form of business is made possible by a market where the quality of infomation is grounded on open reuse and the professional experience of those who produce and transform it. No fences does not mean no rules, just new methods to empower people and their expertise. Our goal is to implement open business models via strategies to transform the opportunities offered by a networked market and systematically capture their values.'}
- {id: '4', intro: 'We are civic entrepreneurs, that’s our values and our protocols.', total: '<big>Will you join us?</big>'}
  
manifesto-download:
- {icon: '<i class="fa fa-file-pdf-o"></i> en', link: 'manifesto_2015_v1_eng.pdf'}
- {icon: '<i class="fa fa-file-image-o"></i> en', link: 'manifesto_2015_v1_eng.png'}
- {icon: '<i class="fa fa-file-pdf-o"></i> it', link: 'manifesto_2015_v1_ita.pdf'}
- {icon: '<i class="fa fa-file-image-o"></i> it', link: 'manifesto_2015_v1_ita.png'}





#-------------------------------
# Work Section

projects:
- {name: Archeostickers, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Datastickers, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Masterplan, folder: 'proj-3', file: 'work/proj-3.html'}
#- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
#- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
#- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
#- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
#- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Travis was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: '<i class="fa fa-twitter"></i>', link: 'http://twitter.com/osd_it'}
- {icon: '<i class="fa fa-github"></i>', link: 'https://github.com/orgs/opensensorsdata'}
- {icon: '<i class="fa fa-medium"></i>', link: 'https://medium.com/opensensorsdata-review'}
- {icon: '<i class="fa fa-facebook-official"></i>', link: 'https://www.facebook.com/opensensorsdata'}
- {icon: '<i class="fa fa-linkedin"></i>', link: 'https://www.linkedin.com/company/opensensorsdata-srl'}


crew:
- {face: 'corsato_thumb.svg', 
  name: 'luca corsato', 
  rule: 'a man with a mustache', 
  twitter: 'lucacorsato', 
  linkedin: 'https://it.linkedin.com/in/lucacorsato',
  github: 'lucacorsato',
  mail: 'luca@opensensorsdata.it'}
- {face: 'raimondi_thumb.svg', 
  name: 'andrea raimondi', 
  rule: 'climbler metaphysician', 
  twitter: 'raimondiand', 
  linkedin: 'https://www.linkedin.com/pub/andrea-raimondi/31/177/199',
  github: 'raimondiand',
  mail: 'andrea@opensensorsdata.it'}
- {face: 'cortesi_thumb.svg', 
  name: 'simone cortesi', 
  rule: 'dr. manhattan', 
  twitter: 'simonecortesi', 
  linkedin: 'https://www.linkedin.com/in/simonecortesi/en',
  github: 'cortesimone',
  mail: 'simone@opensensorsdata.it'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
